# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import API.ficheros.fotosDePerfil.Fotos_De_Perfil_pb2 as Fotos__De__Perfil__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in Fotos_De_Perfil_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FotosDePerfilStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubirFotoDeUsuario = channel.unary_unary(
                '/FotosDePerfil/SubirFotoDeUsuario',
                request_serializer=Fotos__De__Perfil__pb2.FotoDePerfilDatos.SerializeToString,
                response_deserializer=Fotos__De__Perfil__pb2.FotoDePerfilRuta.FromString,
                _registered_method=True)
        self.ObtenerFotoDePerfilUsuario = channel.unary_unary(
                '/FotosDePerfil/ObtenerFotoDePerfilUsuario',
                request_serializer=Fotos__De__Perfil__pb2.FotoDePerfilRuta.SerializeToString,
                response_deserializer=Fotos__De__Perfil__pb2.FotoDePerfilDatos.FromString,
                _registered_method=True)
        self.ActualizarFotoDePerfil = channel.unary_unary(
                '/FotosDePerfil/ActualizarFotoDePerfil',
                request_serializer=Fotos__De__Perfil__pb2.ActualizacionFotoDePerfil.SerializeToString,
                response_deserializer=Fotos__De__Perfil__pb2.FotoDePerfilRuta.FromString,
                _registered_method=True)


class FotosDePerfilServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SubirFotoDeUsuario(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ObtenerFotoDePerfilUsuario(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ActualizarFotoDePerfil(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FotosDePerfilServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubirFotoDeUsuario': grpc.unary_unary_rpc_method_handler(
                    servicer.SubirFotoDeUsuario,
                    request_deserializer=Fotos__De__Perfil__pb2.FotoDePerfilDatos.FromString,
                    response_serializer=Fotos__De__Perfil__pb2.FotoDePerfilRuta.SerializeToString,
            ),
            'ObtenerFotoDePerfilUsuario': grpc.unary_unary_rpc_method_handler(
                    servicer.ObtenerFotoDePerfilUsuario,
                    request_deserializer=Fotos__De__Perfil__pb2.FotoDePerfilRuta.FromString,
                    response_serializer=Fotos__De__Perfil__pb2.FotoDePerfilDatos.SerializeToString,
            ),
            'ActualizarFotoDePerfil': grpc.unary_unary_rpc_method_handler(
                    servicer.ActualizarFotoDePerfil,
                    request_deserializer=Fotos__De__Perfil__pb2.ActualizacionFotoDePerfil.FromString,
                    response_serializer=Fotos__De__Perfil__pb2.FotoDePerfilRuta.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'FotosDePerfil', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('FotosDePerfil', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FotosDePerfil(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SubirFotoDeUsuario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FotosDePerfil/SubirFotoDeUsuario',
            Fotos__De__Perfil__pb2.FotoDePerfilDatos.SerializeToString,
            Fotos__De__Perfil__pb2.FotoDePerfilRuta.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ObtenerFotoDePerfilUsuario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FotosDePerfil/ObtenerFotoDePerfilUsuario',
            Fotos__De__Perfil__pb2.FotoDePerfilRuta.SerializeToString,
            Fotos__De__Perfil__pb2.FotoDePerfilDatos.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ActualizarFotoDePerfil(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FotosDePerfil/ActualizarFotoDePerfil',
            Fotos__De__Perfil__pb2.ActualizacionFotoDePerfil.SerializeToString,
            Fotos__De__Perfil__pb2.FotoDePerfilRuta.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
