# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Fotos_De_Perfil.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'Fotos_De_Perfil.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x46otos_De_Perfil.proto\";\n\x11\x46otoDePerfilDatos\x12\x17\n\x0fnombreDeUsuario\x18\x01 \x01(\t\x12\r\n\x05\x64\x61tos\x18\x02 \x01(\x0c\"^\n\x19\x41\x63tualizacionFotoDePerfil\x12\x17\n\x0fnombreDeUsuario\x18\x01 \x01(\t\x12\x19\n\x11rutaImagenAntigua\x18\x02 \x01(\t\x12\r\n\x05\x64\x61tos\x18\x03 \x01(\x0c\"\'\n\x10\x46otoDePerfilRuta\x12\x13\n\x0brutaArchivo\x18\x01 \x01(\t2\xda\x01\n\rFotosDePerfil\x12;\n\x12SubirFotoDeUsuario\x12\x12.FotoDePerfilDatos\x1a\x11.FotoDePerfilRuta\x12\x43\n\x1aObtenerFotoDePerfilUsuario\x12\x11.FotoDePerfilRuta\x1a\x12.FotoDePerfilDatos\x12G\n\x16\x41\x63tualizarFotoDePerfil\x12\x1a.ActualizacionFotoDePerfil\x1a\x11.FotoDePerfilRutab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Fotos_De_Perfil_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FOTODEPERFILDATOS']._serialized_start=25
  _globals['_FOTODEPERFILDATOS']._serialized_end=84
  _globals['_ACTUALIZACIONFOTODEPERFIL']._serialized_start=86
  _globals['_ACTUALIZACIONFOTODEPERFIL']._serialized_end=180
  _globals['_FOTODEPERFILRUTA']._serialized_start=182
  _globals['_FOTODEPERFILRUTA']._serialized_end=221
  _globals['_FOTOSDEPERFIL']._serialized_start=224
  _globals['_FOTOSDEPERFIL']._serialized_end=442
# @@protoc_insertion_point(module_scope)
