version: '3.0'

services:
  
  gamelog_db:
    build:
      context:  ./APIRest/initdb-scripts
    container_name: gamelog_db
    restart: always
    ports:
      - 1433:1433
    environment:
      - SA_PASSWORD=.JUg4d0rL0000g.
      - ACCEPT_EULA=Y

  gamelog_apigrpc:
    build:
      context: ./ApigRPC
    container_name: gamelog_apigrpc
    restart: always
    ports:
      - 1235:1235

  gamelog_apirest:
    build:
      context: ./APIRest
    container_name: gamelog_apirest
    restart: always
    ports:
      - 1234:1234
    depends_on:
      - gamelog_db
  
  nginx:
    image: nginx:latest
    container_name: gamelog_nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./Nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - gamelog_apirest
      - gamelog_apigrpc

