Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"

    config.vm.hostname = "gamelog-vm"

    config.vm.network "forwarded_port", guest: 80, host: 8080
    config.vm.network "forwarded_port", guest: 443, host: 8443

    config.vm.synced_folder ".", "/vagrant", type: "virtualbox"

    config.vm.provider "virtualbox" do |vb|
        vb.memory = 4096 
        vb.cpus = 4
    end

    config.vm.provision "shell", inline: <<-SHELL
        apt-get update
        apt-get install -y docker.io docker-compose
        usermod -aG docker vagrant
        cd /vagrant
        docker-compose up -d --build
    SHELL
end