Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"
    config.vm.hostname = "gamelog-vm"

    config.vm.network "public_network"

    config.vm.network "forwarded_port", guest: 80, host: 8080
    config.vm.network "forwarded_port", guest: 443, host: 8443

    config.vm.synced_folder ".", "/vagrant", type: "virtualbox"

    config.vm.provider "virtualbox" do |vb|
        vb.memory = 4096 
        vb.cpus = 4
    end

    config.vm.provision "shell", inline: <<-SHELL
        apt-get update
        apt-get install -y docker.io docker-compose
        apt-get install -y language-pack-es
        apt-get install -y openssl ca-certificates
        locale-gen es_ES.UTF-8
        update-locale LANG=es_ES.UTF-8
        sed -i 's/XKBLAYOUT=".*"/XKBLAYOUT="es"/g' /etc/default/keyboard
        usermod -aG docker vagrant
        cd /vagrant
        docker-compose up -d --build
        cp /vagrant/nginx/certs/certificate.crt /usr/local/share/ca-certificates/
        update-ca-certificates
    SHELL
end